cdef char QUOTE
cdef char SEMICOLON
cdef char COLON
cdef char EQUALS
cdef char CURLY_OPEN
cdef char CURLY_CLOSE
cdef char SQUARE_OPEN
cdef char SQUARE_CLOSE
cdef char COMMA
cdef char PLUS
cdef char MINUS
cdef char SLASH
cdef char DOLLAR
cdef char ASTERISK
cdef char NEWLINE

cdef bytes NEWLINE_U
cdef bytes END_COMMENT_U
cdef bytes QUOTE_U
cdef bytes STR
