name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install testing framework
        run: python -m pip install pytest

      - name: Run pure python tests
        run: pytest

      - name: Install Cython
        run: python -m pip install -r requirements-cython.txt

      - name: Run pure python tests with Cython installed
        run: pytest

      - name: Build the extension
        run: python setup_cython.py build_ext --inplace --force

      - name: Run Cythonized library tests
        run: pytest

      - name: Run performance test
        run: python testconfig.py
