name: Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install testing framework
        run: python -m pip install pytest

      - name: Run pure python tests
        run: pytest

      - name: Install Cython
        run: python -m pip install -r requirements-cython.txt

      - name: Run pure python tests with Cython installed
        run: pytest

      - name: Build the extension
        run: python setup_cython.py build_ext --inplace --force

      - name: Run Cythonized library tests
        run: pytest

      - name: Run performance test
        run: python testconfig.py

  build_source_distribution:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build SDist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install -r requirements-cython.txt
          CIBW_SKIP: pp*
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}


      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
