name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Build the extension
        run: python setup.py build_ext --inplace --force

      - name: Run tests
        run: pytest

      - name: Run performance test
        run: python testconfig.py
